# Defect Detection Based On Extreme Edge of Defective Region Histogram
Run the code:
Type in the command window
Z_H_test
enter
Then type the name of testing imge like
e3.png
enter 

When you use this code or any part of it, please cite the following article:  
Zouhir Wakaf, Hamid A. Jalab(2016). Defect Detection Based On Extreme Edge of Defective Region Histogram. Journal of King Saud University - Computer and Information Sciences. DOI: 10.1016/j.jksuci.2016.11.001
